.PHONY: clean All

All:
	@echo "==========Building project:[ CPP-dsa-lehren - Debug ]=========="
	@cd "CPP-dsa-lehren" && "$(MAKE)" -f  "CPP-dsa-lehren.mk"
clean:
	@echo "==========Cleaning project:[ CPP-dsa-lehren - Debug ]----------"
	@cd "CPP-dsa-lehren" && "$(MAKE)" -f  "CPP-dsa-lehren.mk" clean
